# Generated by Django 4.2.7 on 2023-11-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_usuarios_usuario_horastrabajada'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='valor_x_hora',
            field=models.PositiveIntegerField(default=30000),
        ),
    ]
