# Generated by Django 4.2.7 on 2023-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_usuario_valor_x_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='horastrabajada',
            name='valor_x_hora',
            field=models.PositiveIntegerField(default=30000),
        ),
    ]
