# Generated by Django 4.2.7 on 2023-11-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_horastrabajada_valor_x_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='valor_x_hora',
        ),
    ]
