# Generated by Django 4.2.7 on 2023-12-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=0, max_length=200)),
                ('correo', models.EmailField(default=0, max_length=254)),
                ('celular', models.DateTimeField()),
                ('año_nacimiento', models.DateTimeField()),
            ],
        ),
    ]
