# Generated by Django 4.2.7 on 2023-12-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cancion_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='puntuacion',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
