# Generated by Django 4.2.7 on 2023-11-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('celular', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
    ]
