# Generated by Django 4.2.7 on 2023-11-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_celular_cliente_celular_cli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email_cli',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cli',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie_mas',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre_mas',
            field=models.CharField(max_length=200),
        ),
    ]
