# Generated by Django 4.2.7 on 2023-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_usuarios_altura_horastrabajadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=165.0, max_digits=5),
        ),
    ]
