# Generated by Django 4.2.7 on 2023-11-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_usuarios_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='valorHora',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=165.0, max_digits=5),
        ),
    ]
