# Generated by Django 4.2.7 on 2023-11-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.PositiveIntegerField()),
                ('altura', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('valor_x_hora', models.PositiveIntegerField(default=30000)),
            ],
        ),
        migrations.CreateModel(
            name='HorasTrabajada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_horas', models.PositiveIntegerField()),
                ('dia', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
    ]
