# Generated by Django 4.2.7 on 2023-11-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nuevo',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
