# Generated by Django 4.2.7 on 2023-11-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuario_nuevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nuevo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='valor_x_hora',
        ),
        migrations.AddField(
            model_name='usuario',
            name='barrio',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dirección',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
