# Generated by Django 4.2.7 on 2023-11-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='peso',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
