# Generated by Django 4.2.7 on 2023-12-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_regalos_regalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='regalo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
