# Generated by Django 4.2.7 on 2023-12-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_regalo_regalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regalo',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección Web'),
        ),
    ]
