# Generated by Django 4.2.7 on 2023-12-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_regalo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.CharField(default='', max_length=50)),
                ('decripcion', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
