# Generated by Django 4.2.7 on 2023-11-24 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='especie_mas',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento_mas',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='peso_mas',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='propietario',
            name='celular_cli',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='email_cli',
            field=models.EmailField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='fecha_nacimiento_cli',
            field=models.DateField(default=None, null=True),
        ),
    ]
