# Generated by Django 4.2.7 on 2023-11-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fechanacimiento',
            field=models.DateField(default=21071973),
            preserve_default=False,
        ),
    ]
