# Generated by Django 4.2.7 on 2023-11-19 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='celular',
            new_name='celular_cli',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='email_cli',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='fechanacimiento',
            new_name='fecha_nacimiento_cli',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombre_cli',
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mas', models.CharField(max_length=200, unique=True)),
                ('fecha_nacimiento_mas', models.DateField()),
                ('especie_mas', models.CharField(max_length=200, unique=True)),
                ('peso_mas', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cliente')),
            ],
        ),
    ]
