# Generated by Django 4.2.7 on 2023-11-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='horas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
