# Generated by Django 4.2.7 on 2023-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_suscriptor_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='nrohoras',
            field=models.CharField(max_length=10),
        ),
    ]
