# Generated by Django 4.2.7 on 2023-11-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuarios_altura'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasTrabajadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_horas', models.PositiveIntegerField()),
                ('dia', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuarios')),
            ],
        ),
    ]
