# Generated by Django 4.2.7 on 2023-11-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_horastrabajadas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HorasTrabajadas',
            new_name='HorasTrabajada',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
