# Generated by Django 4.2.7 on 2023-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_horastrabajadas_horastrabajada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=160.0, max_digits=5),
        ),
    ]
